Opening hours
shopgun/tjek-swift-sdk pull request #47
Opened 2022-03-07 21:25 UTC by mazvydasb

Test are still missing, but it's ready for initial review.

2022-03-08 14:11 UTC, lozhuf commented on Sources/TjekAPI/Models/v2Models.swift
> +#warning("Make Tests")
Dont forget this!

2022-03-14 09:52 UTC, lozhuf requested changes

2022-03-14 09:52 UTC, lozhuf commented on Tests/TjekAPITests/OpeningHoursTests.swift
> +        XCTAssertNoThrow(try decoder.decode(OpeningHours_v2.self, from: maxJson.data(using: .utf8)!))
These are kind of unnecessary - the func `testOpeningHoursDecodable` being marked as `throws` is basically the same as calling `XCTAssertNoThrow`. 

And the XCTAssertNotEqual isn't something we really need to test - you are making those `expected*` values yourself above (and therefore know they are not equal), and so by transitive logic, if `openingHours == expectedDateRange` & `expectedDateRange != expectedWeekday`, then `openingHours != expectedWeekday`, so no need for the test.

2022-03-14 09:52 UTC, lozhuf commented on Tests/TjekAPITests/OpeningHoursTests.swift
> +        XCTAssertNoThrow(try decoder.decode(OpeningHours_v2.self, from: maxJson.data(using: .utf8)!))
The same for the other 2 test cases below... and with that, you also dont need to declare all your `expected values at the top - I think for clarity sake defining them next to the json that makes them would be cleaner.

If you really want to clean it up and get fancy, you could just make an inline function that takes a json string and an expected OpeningHours value, and do the decode & assert in there.

2022-03-14 09:52 UTC, lozhuf commented on Tests/TjekAPITests/OpeningHoursTests.swift
> +        XCTAssertFalse(openingHours.contains(date: Date()))
Maybe also assert a happy-path for the `mondayHours` type - eg. make a test date that IS on a Monday, and assert that it is matched.

2022-03-14 09:52 UTC, lozhuf commented on Sources/TjekAPI/Models/v2Models.swift
> +            self.period = .dateRange(validFrom...validUntil)
I would also recommend handling the case where validFrom > validUntil... Swift.Range will fatal error if you make one with a larger start value - in the past we've had the server crash the app because they sent invalid dates. To fix this you just need to make your date range like this:
```swift
self.period = .dateRange(min(validFrom, validUntil)...max(validFrom, validUntil))
```

2022-03-14 19:33 UTC, lozhuf approved these changes

2022-03-15 08:16 UTC, lozhuf requested changes

2022-03-15 09:24 UTC, mazvydasb commented on Sources/TjekAPI/Models/v2Models.swift
> +           calendar.weekdaySymbols[self.weekdayComponent - 1]
Good point.

2022-03-15 12:46 UTC, lozhuf commented on Sources/TjekAPI/Models/v2Models.swift
> +        public func date(relativeTo date: Date = Date(), usingCalendar: Calendar) -> Date? {
Minor comment - any time you are referring to `weekdayComponent` I think you need to make a Gregorian calendar, rather than have one passed in (if its non-gregorian then weekday components will mismatch)

2022-03-15 12:48 UTC, lozhuf commented on Sources/TjekAPI/Models/v2Models.swift
> +        public func date(on day: Date, usingCalendar: Calendar) -> Date? {
This calendar can probably have a default value, eg. `.autoupdatingCurrent`

2022-03-16 13:15 UTC, lozhuf approved these changes

2022-03-16 14:19 UTC, merged